name: CD

on:
  workflow_dispatch:
  repository_dispatch:
    types: [start-cd]

jobs:
  deploy:
    name: Deploy commit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Restore cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-cache-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_SERVER_KEY: ${{ secrets.REACT_APP_SERVER_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
